version: '3.9'

services:
  redis:
    restart: unless-stopped
    image: redis:7.0.11-alpine
    container_name: redis-container
    ports:
      - '6399:6379'
    networks:
      - djangonetwork

  django:
    restart: unless-stopped
    container_name: django-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/django-entrypoint.sh
    volumes:
      - .:/app
    ports:
      - 8000:8000
    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
    networks:
      - djangonetwork

    depends_on:
      - redis
  celery:
    restart: unless-stopped
    container_name: celery-container
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    entrypoint: /app/docker/worker-entrypoint.sh
    volumes:
      - .:/app

    env_file:
      - .env
    environment:
      DEBUG: ${DEBUG}
      SECRET_KEY: ${SECRET_KEY}
      ALLOWED_HOSTS: ${ALLOWED_HOSTS}
      CELERY_BROKER_URL: ${CELERY_BROKER_URL}
      CELERY_RESULT_BACKEND: ${CELERY_RESULT_BACKEND}
    networks:
      - djangonetwork
    depends_on:
      - redis
      - django

networks:
  djangonetwork:
    name: djangonetwork
    driver: bridge
